<%@ Page Title="Customer Form"
    Language="C#"
    MasterPageFile="~/landing.master"
    AutoEventWireup="true"
    CodeFile="CustomerForm.aspx.cs"
    Inherits="Pages_CustomerForm" %>

<asp:Content ID="Content1"
    ContentPlaceHolderID="head"
    runat="Server">

    <style>
        .customer-form-title {
            font-size: 24px;
            font-weight: 600;
            margin-bottom: 5px;
        }

        .customer-form-subtitle {
            color: #6c757d;
            margin-bottom: 0;
        }

        .form-label {
            font-weight: 500;
        }

        .required {
            color: #ff3e1d;
        }

        .validation-message {
            color: #ff3e1d;
            font-size: 13px;
            margin-top: 5px;
            display: block;
        }

        .success-message {
            color: #71dd37;
            font-size: 14px;
        }

        .error-message {
            color: #ff3e1d;
            font-size: 14px;
        }

        .form-actions {
            display: flex;
            justify-content: flex-end;
            gap: 10px;
            margin-top: 25px;
        }
    </style>

</asp:Content>


<asp:Content ID="Content2"
    ContentPlaceHolderID="ContentPlaceHolder1"
    runat="Server">

    <div class="container-xxl flex-grow-1 container-p-y">

        <!-- Page Header -->
        <div class="mb-4">

            <h4 class="customer-form-title">
                <asp:Literal
                    ID="litPageTitle"
                    runat="server"
                    Text="Add Customer">
                </asp:Literal>
            </h4>

            <p class="customer-form-subtitle">
                Add or update customer information.
            </p>

        </div>


        <!-- Customer Form Card -->
        <div class="card">

            <div class="card-body">

                <!-- Message -->
                <asp:Label
                    ID="lblMessage"
                    runat="server"
                    Visible="false">
                </asp:Label>


                <!-- Customer Information -->
                <h5 class="mb-4">Customer Information
                </h5>


                <div class="row g-4">


                    <!-- Customer Code -->
                    <div class="col-md-6">

                        <label class="form-label">
                            Customer Code
                        </label>

                        <asp:TextBox
                            ID="txtCustomerCode"
                            runat="server"
                            CssClass="form-control"
                            ReadOnly="true">
                        </asp:TextBox>

                        <small class="text-muted">Automatically generated by the system.
                        </small>

                    </div>


                    <!-- Customer Name -->
                    <div class="col-md-6">

                        <label class="form-label">
                            Customer Name
                            <span class="required">*</span>
                        </label>

                        <asp:TextBox
                            ID="txtCustomerName"
                            runat="server"
                            CssClass="form-control"
                            MaxLength="150"
                            placeholder="Enter customer name">
                        </asp:TextBox>

                        <asp:RequiredFieldValidator
                            ID="rfvCustomerName"
                            runat="server"
                            ControlToValidate="txtCustomerName"
                            ErrorMessage="Customer name is required."
                            CssClass="validation-message"
                            Display="Dynamic">
                        </asp:RequiredFieldValidator>

                    </div>


                    <!-- Phone -->
                    <div class="col-md-6">

                        <label class="form-label">
                            Phone
                            <span class="required">*</span>
                        </label>

                        <asp:TextBox
                            ID="txtPhone"
                            runat="server"
                            CssClass="form-control"
                            MaxLength="20"
                            placeholder="Enter phone number">
                        </asp:TextBox>

                        <asp:RequiredFieldValidator
                            ID="rfvPhone"
                            runat="server"
                            ControlToValidate="txtPhone"
                            ErrorMessage="Phone number is required."
                            CssClass="validation-message"
                            Display="Dynamic">
                        </asp:RequiredFieldValidator>

                        <asp:RegularExpressionValidator
                            ID="revPhone"
                            runat="server"
                            ControlToValidate="txtPhone"
                            ValidationExpression="^[6-9][0-9]{9}$"
                            ErrorMessage="Enter a valid 10-digit Indian mobile number starting with 6, 7, 8, or 9."
                            CssClass="validation-message"
                            Display="Dynamic">
                        </asp:RegularExpressionValidator>

                    </div>


                    <!-- Email -->
                    <div class="col-md-6">

                        <label class="form-label">
                            Email
                        </label>

                        <asp:TextBox
                            ID="txtEmail"
                            runat="server"
                            CssClass="form-control"
                            MaxLength="150"
                            placeholder="Enter email address">
                        </asp:TextBox>

                        <asp:RegularExpressionValidator
                            ID="revEmail"
                            runat="server"
                            ControlToValidate="txtEmail"
                            ValidationExpression="^[^@\s]+@[^@\s]+\.[^@\s]+$"
                            ErrorMessage="Enter a valid email address."
                            CssClass="validation-message"
                            Display="Dynamic">
                        </asp:RegularExpressionValidator>

                    </div>


                    <!-- Address -->
                    <div class="col-12">

                        <label class="form-label">
                            Address
                        </label>

                        <asp:TextBox
                            ID="txtAddress"
                            runat="server"
                            CssClass="form-control"
                            TextMode="MultiLine"
                            Rows="3"
                            MaxLength="250"
                            placeholder="Enter complete address">
                        </asp:TextBox>

                        <asp:RequiredFieldValidator 
                            ID="rvAddress" 
                            runat="server" 
                            ControlToValidate="txtAddress"
                            ErrorMessage="Address is required"
                            CssClass="validation-message"
                            Display="Dynamic"
                            ></asp:RequiredFieldValidator>

                    </div>


                    <!-- City -->
                    <div class="col-md-4">

                        <label class="form-label">
                            City
                        </label>

                        <asp:TextBox
                            ID="txtCity"
                            runat="server"
                            CssClass="form-control"
                            MaxLength="100"
                            placeholder="Enter city">
                        </asp:TextBox>

                    </div>


                    <!-- State -->
                    <div class="col-md-4">

                        <label class="form-label">
                            State
                        </label>

                        <asp:TextBox
                            ID="txtState"
                            runat="server"
                            CssClass="form-control"
                            MaxLength="100"
                            placeholder="Enter state">
                        </asp:TextBox>

                    </div>


                    <!-- Pin Code -->
                    <div class="col-md-4">

                        <label class="form-label">
                            PIN Code
                        </label>

                        <asp:TextBox
                            ID="txtPinCode"
                            runat="server"
                            CssClass="form-control"
                            MaxLength="6"
                            placeholder="Enter 6-digit PIN code">
                        </asp:TextBox>

                        <asp:RegularExpressionValidator
                            ID="revPinCode"
                            runat="server"
                            ControlToValidate="txtPinCode"
                            ValidationExpression="^[0-9]{6}$"
                            ErrorMessage="Enter a valid 6-digit PIN code."
                            CssClass="validation-message"
                            Display="Dynamic">
                        </asp:RegularExpressionValidator>

                    </div>


                    <!-- GSTIN -->
                    <div class="col-md-6">

                        <label class="form-label">
                            GSTIN
                        </label>

                        <asp:TextBox
                            ID="txtGSTIN"
                            runat="server"
                            CssClass="form-control"
                            MaxLength="15"
                            placeholder="Enter 15-character GSTIN if applicable"
                            Style="text-transform: uppercase;">
                        </asp:TextBox>

                        <asp:RegularExpressionValidator
                            ID="revGSTIN"
                            runat="server"
                            ControlToValidate="txtGSTIN"
                            ValidationExpression="^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$"
                            ErrorMessage="Enter a valid GSTIN."
                            CssClass="validation-message"
                            Display="Dynamic">
                        </asp:RegularExpressionValidator>

                    </div>

                </div>


                <!-- Buttons -->
                <div class="form-actions">

                    <asp:HyperLink
                        ID="lnkCancel"
                        runat="server"
                        NavigateUrl="~/Pages/Customers.aspx"
                        CssClass="btn btn-outline-secondary">

                        Cancel

                    </asp:HyperLink>


                    <asp:Button
                        ID="btnSave"
                        runat="server"
                        Text="Save Customer"
                        CssClass="btn btn-primary"
                        OnClick="btnSave_Click"></asp:Button>

                </div>

            </div>

        </div>

    </div>

</asp:Content>
